### PR TITLE
Change Color access modifier to public

### PR DESCRIPTION
**Pull request by sheshnathverma**
# Types of Changes

Change Color structure access modifier to public

FYI @FlorianRappl here is the pull request for bug id #105

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Looks great, but you'll need to sign the CLA. For the CLA bot to recognize you your git email address needs to be linked to your GitHub account.

**Comment by sheshnathverma** [comment]
@FlorianRappl I have signed Contributor License Agreement multiple time but still it is saying not signed

**Comment by jogibear9988** [comment]
As Florian said, do you use a different email in your git settings as in your github account

**Comment by FlorianRappl** [comment]
Yeah its a bit unfortunate - but thats the design of the CLA Assistant:

- You sign the CLA with your GitHub account
- Your commits (done via some email as you configured locally) are then implicitly signed if the email is associated with that GitHub account

So when you use "foo@bar.com" as an email, you must have your GitHub account associated with it. Otherwise, GitHub does not know that you are the committer (i.e., that this commit was done by you). Note: You can associated multiple email addresses with one GitHub account - you already have one by default (the email you registered with).

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account

(Sometimes people enter weird email addresses or leave them blank / have `user@localhost` etc. - if this is the case you won't be able to sign the commit; just re-configure etc.)

**Pull request closed without merging**
