### PR TITLE
fix grid area, fixes #85

### LINKED ISSUE #85: Grid Area wrong parsed
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Grid area is converted to wrong css

## Steps to Reproduce

Try this snippet:

            var source = "#nav-header {grid-area: navheader; }";
            var css = ParseStyleSheet(source);
            var text = css.Rules[0].CssText;

**Expected behavior:** [What you expected to happen]

I expect the text to be the same as in source (or nearly)

**Actual behavior:** [What actually happened]

the text look like this:

       #nav-header { grid-area: navheader / navheader / auto / auto }

problem is, this text renders the html differently then the original one (at least in chrome)

### PR DESCRIPTION
**Pull request by jogibear9988**
# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## Description

fix grid area

### CODE REVIEW

**Comment by jogibear9988** [comment]
Don't know if this is good like it is...

but who is responsible for minification of the property, so if I write it with the MinifyStyleFormatter, only one value is in the text?

**Comment by jogibear9988** [comment]
@FlorianRappl 
don't know if you have another check if a css value is a number, so I used int.parse...

but I think this will not work then:

in chrome I can do this:

$0.style.gridArea='99999999999999999999999999999999999'
and
window.getComputedStyle($0).gridArea
will return:
'1000 / auto / auto / auto'

**Comment by jogibear9988** [comment]
so also according to the spec, should we limit the value?
https://www.w3.org/TR/css-grid-1/#overlarge-grids

**Comment by FlorianRappl** [comment]
I think the clamping makes sense. We should have this, too.

Regarding number check: There are many micro-parsers that do that. One example is the `UnitParser` (https://github.com/AngleSharp/AngleSharp.Css/blob/8dc13db5807a3f687eb0b4751a42a15e080f28fe/src/AngleSharp.Css/Parser/Micro/UnitParser.cs#L12), which can parse and generate a unit (can also be dimension-less, which is a number).

**Comment by jogibear9988** [comment]
@FlorianRappl 

would this be better?

      UnitParser.ParseUnit(new StringSource(tuple.Items[0].CssText));
      (or ParseLength)

or is my int.parse okay?

at least the upper one doesn't work at all...

**Comment by jogibear9988** [comment]
@FlorianRappl any news?

**Comment by FlorianRappl** [comment]
Ah sorry forgot to reply:

Hm usually you are already in a parser context. Not sure why you do the string to stringsource conversion, as you should already have a string source. If you do all that *after* you got a value then something may be wrong - as the value may not be a valid one anyway.

In any case `ParseLength` is suitable if its a length unit - the unit parser is the generic one IIRC.

**Comment by jogibear9988** [comment]
I don't know where you'd like the chance to be. I tried to do it with minimal impact. If no time at the moment to dig so deep into AngleSharp. But my fix works, and does return correct css ( without it's wrong)

And hyve you also seen, I've 3 other pull req's with questions.

**Comment by FlorianRappl** [comment]
> And have you also seen, I've 3 other pull req's with questions.

Thanks for bringing this up - I did not see them until now. Looks good!

> But my fix works, and does return correct css ( without it's wrong)

That's great - fine with me. All I did was answering your question. Let me know if that works for you.

**Comment by jogibear9988** [comment]
Then this could be merged. It works. It could be improved later if needed

**Comment by FlorianRappl** [comment]
> Then this could be merged. It works. It could be improved later if needed

Alright, then let's do that!

**Review by FlorianRappl — APPROVED** [review]

**Pull request merged**
